### ISSUE TITLE
Erros ao compilar. 

### ISSUE THREAD

**Issue by paulolezak** [erlonfs/first-candle.bad-robot#12]
'ENUM_LAST_PRICE_TYPE' - unexpected token, probably type is missing?	BadRobotCore.mqh	33	2
'ENUM_LAST_PRICE_TYPE' - declaration without type	BadRobotCore.mqh	1354	24
'Logger' - parameter passed as reference, variable expected	BadRobotCore.mqh	1194	17

'value' - undeclared identifier	BadRobotCore.mqh	1356	20

**Comment by erlonfs** [comment]
Fixed!
